title: Technovating Arup_Parida
author: GitHub User_New_learner
email: arupxml@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here to build cool stuff, learn everyday and share the world of techno-innovation with you.
  


  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
  
  
  looking to make a list of blogs that i want to start with and how we will manage it 
  So will categorize it to coding lang prefereable python, c ,html, css, javascript
  and what ever i learn here on github
  also 

so how to manage it and add graphics and other things 


# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Arupparida # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
